from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

from .analyzer import analyze_case, write_csv
from .inventory import summarize_zip
from .parser import split_combined_text_by_reset
from .pdf_import import write_pdf_text
from .docx_import import write_docx_text
from .util import read_text_file
from .workbook import make_output_workbook


def cmd_inventory(args: argparse.Namespace) -> int:
    rows = summarize_zip(args.artifact_zip, args.extensions)
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        with out.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()) if rows else ["case_folder"])
            writer.writeheader()
            writer.writerows(rows)
    else:
        for row in rows:
            print(json.dumps(row, ensure_ascii=False))
    return 0


def cmd_analyze(args: argparse.Namespace) -> int:
    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)
    docket_text_path = _resolve_docket_source(args, outdir, args.case_name)

    full, keep, review, skipped, summary = analyze_case(
        case_name=args.case_name,
        case_folder=args.case_folder or args.case_name,
        docket_text_path=docket_text_path,
        artifact_zip_path=args.artifact_zip,
        rules_path=args.rules,
        artifact_extensions=args.extensions,
    )
    slug = _slug(args.case_name)
    write_csv(outdir / f"{slug}_full_comparison.csv", full)
    write_csv(outdir / f"{slug}_keep_request.csv", keep)
    write_csv(outdir / f"{slug}_review_optional.csv", review)
    write_csv(outdir / f"{slug}_skipped.csv", skipped)
    (outdir / f"{slug}_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    make_output_workbook(
        outdir / f"{slug}_download_request.xlsx",
        {args.case_name: keep},
        [summary],
        ["Generated by docket-gap-tool analyze. Review optional rows are excluded from final by default."],
    )
    print(json.dumps(summary, indent=2))
    return 0


def cmd_batch(args: argparse.Namespace) -> int:
    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)
    manifest = json.loads(Path(args.manifest).read_text(encoding="utf-8"))
    case_rows: dict[str, list[dict]] = {}
    summaries: list[dict] = []
    all_full: list[dict] = []
    all_review: list[dict] = []
    all_skipped: list[dict] = []

    for item in manifest["cases"]:
        docket_text_path = _resolve_manifest_docket_source(item, outdir)
        full, keep, review, skipped, summary = analyze_case(
            case_name=item["case_name"],
            case_folder=item.get("case_folder") or item["case_name"],
            docket_text_path=docket_text_path,
            artifact_zip_path=args.artifact_zip,
            rules_path=args.rules,
            artifact_extensions=args.extensions,
        )
        case_rows[item["case_name"]] = keep
        summaries.append(summary)
        all_full.extend(full)
        all_review.extend(review)
        all_skipped.extend(skipped)
        slug = _slug(item["case_name"])
        write_csv(outdir / f"{slug}_keep_request.csv", keep)
        write_csv(outdir / f"{slug}_review_optional.csv", review)

    write_csv(outdir / "all_final_keep_request.csv", [r for rows in case_rows.values() for r in rows])
    write_csv(outdir / "all_full_comparison.csv", all_full)
    write_csv(outdir / "all_review_optional.csv", all_review)
    write_csv(outdir / "all_skipped.csv", all_skipped)
    make_output_workbook(
        outdir / args.workbook_name,
        case_rows,
        summaries,
        [
            "Generated by docket-gap-tool batch.",
            "Downloaded artifact detection counts both .pdf and .zip files by default.",
            "Rows classified as review_optional are not included in final request/download sheets. Review them if precision is critical.",
        ],
    )
    print(json.dumps({"cases": summaries, "workbook": str(outdir / args.workbook_name)}, indent=2))
    return 0


def cmd_import_docx(args: argparse.Namespace) -> int:
    output = args.output_text
    if not output:
        docx = Path(args.input_docx)
        output = str(docx.with_suffix(".extracted.txt"))
    result = write_docx_text(args.input_docx, output)
    print(json.dumps(result, indent=2))
    return 0


def cmd_import_pdf(args: argparse.Namespace) -> int:
    output = args.output_text
    if not output:
        pdf = Path(args.input_pdf)
        output = str(pdf.with_suffix(".extracted.txt"))
    result = write_pdf_text(args.input_pdf, output, password=args.password, max_pages=args.max_pages, ocr=args.ocr, ocr_dpi=args.ocr_dpi, ocr_language=args.ocr_language)
    print(json.dumps(result, indent=2))
    if result["appears_empty_or_scanned"]:
        print(
            "Warning: extracted text is very short. This may be a scanned/image-only PDF; "
            "use a selectable browser printout or OCR it first.",
            file=sys.stderr,
        )
    return 0


def _resolve_docket_source(args: argparse.Namespace, outdir: Path, case_name: str) -> str:
    sources = [args.docket_text, args.docket_pdf, getattr(args, "docket_docx", None)]
    if sum(bool(x) for x in sources) > 1:
        raise ValueError("Use only one of --docket-text, --docket-pdf, or --docket-docx.")
    if args.docket_text:
        return args.docket_text
    if args.docket_pdf:
        extracted_dir = outdir / "_extracted_text"
        extracted_path = extracted_dir / f"{_slug(case_name)}.txt"
        write_pdf_text(args.docket_pdf, extracted_path, password=args.pdf_password, max_pages=args.pdf_max_pages, ocr=args.ocr, ocr_dpi=args.ocr_dpi, ocr_language=args.ocr_language)
        return str(extracted_path)
    if getattr(args, "docket_docx", None):
        extracted_dir = outdir / "_extracted_text"
        extracted_path = extracted_dir / f"{_slug(case_name)}.txt"
        write_docx_text(args.docket_docx, extracted_path)
        return str(extracted_path)
    raise ValueError("Provide --docket-text, --docket-pdf, or --docket-docx.")


def _resolve_manifest_docket_source(item: dict, outdir: Path) -> str:
    if sum(bool(item.get(k)) for k in ("docket_text", "docket_pdf", "docket_docx")) > 1:
        raise ValueError(f"Manifest case {item.get('case_name')} has multiple docket sources. Use one of docket_text, docket_pdf, or docket_docx.")
    if item.get("docket_text"):
        return item["docket_text"]
    if item.get("docket_pdf"):
        extracted_dir = outdir / "_extracted_text"
        extracted_path = extracted_dir / f"{_slug(item['case_name'])}.txt"
        write_pdf_text(
            item["docket_pdf"],
            extracted_path,
            password=item.get("pdf_password"),
            max_pages=item.get("pdf_max_pages"),
            ocr=item.get("ocr", "auto"),
            ocr_dpi=int(item.get("ocr_dpi", 200)),
            ocr_language=item.get("ocr_language", "eng"),
        )
        return str(extracted_path)
    if item.get("docket_docx"):
        extracted_dir = outdir / "_extracted_text"
        extracted_path = extracted_dir / f"{_slug(item['case_name'])}.txt"
        write_docx_text(item["docket_docx"], extracted_path)
        return str(extracted_path)
    raise ValueError(f"Manifest case {item.get('case_name')} must include docket_text, docket_pdf, or docket_docx.")


def cmd_split(args: argparse.Namespace) -> int:
    text = read_text_file(args.input_text)
    parts = split_combined_text_by_reset(text)
    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)
    for idx, part in enumerate(parts, 1):
        (outdir / f"part_{idx:02d}.txt").write_text(part, encoding="utf-8")
    print(json.dumps({"parts": len(parts), "output_dir": str(outdir)}, indent=2))
    return 0


def _slug(name: str) -> str:
    import re
    s = re.sub(r"[^a-zA-Z0-9]+", "_", name).strip("_").lower()
    return s or "case"



def cmd_auto(args: argparse.Namespace) -> int:
    from .easy_run import main as easy_main
    return easy_main([])

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="docket-gap", description="Local bankruptcy docket gap checker.")
    sub = p.add_subparsers(dest="command", required=True)

    inv = sub.add_parser("inventory", help="Inventory downloaded PDF/ZIP artifacts inside a case ZIP.")
    inv.add_argument("--artifact-zip", required=True)
    inv.add_argument("--output", help="Optional CSV path")
    inv.add_argument("--extensions", nargs="+", default=[".pdf", ".zip"], help="Extensions to count as downloaded artifacts")
    inv.set_defaults(func=cmd_inventory)

    imp = sub.add_parser("import-pdf", help="Extract selectable text from a docket PDF printout.")
    imp.add_argument("--input-pdf", required=True)
    imp.add_argument("--output-text", help="Output .txt path. Defaults to <pdf>.extracted.txt")
    imp.add_argument("--password", help="Password if the PDF is encrypted")
    imp.add_argument("--max-pages", type=int, help="Optional page limit for testing")
    imp.add_argument("--ocr", choices=["auto", "force", "off"], default="auto", help="Use Tesseract OCR as backup when PDF text extraction is empty/short")
    imp.add_argument("--ocr-dpi", type=int, default=200, help="OCR render DPI")
    imp.add_argument("--ocr-language", default="eng", help="Tesseract language code, e.g. eng")
    imp.set_defaults(func=cmd_import_pdf)

    impd = sub.add_parser("import-docx", help="Extract text from a Word .docx docket export.")
    impd.add_argument("--input-docx", required=True)
    impd.add_argument("--output-text", help="Output .txt path. Defaults to <docx>.extracted.txt")
    impd.set_defaults(func=cmd_import_docx)

    an = sub.add_parser("analyze", help="Analyze one case.")
    an.add_argument("--artifact-zip", required=True)
    an.add_argument("--case-folder", help="Exact folder name inside artifact ZIP")
    an.add_argument("--case-name", required=True, help="Display name for output")
    an.add_argument("--docket-text", help="Bloomberg docket text file")
    an.add_argument("--docket-pdf", help="Browser printout PDF of the Bloomberg docket page")
    an.add_argument("--docket-docx", help="Word .docx docket export")
    an.add_argument("--pdf-password", help="Password if the docket PDF is encrypted")
    an.add_argument("--pdf-max-pages", type=int, help="Optional page limit for PDF extraction/testing")
    an.add_argument("--ocr", choices=["auto", "force", "off"], default="auto", help="Use Tesseract OCR as backup when PDF text extraction is empty/short")
    an.add_argument("--ocr-dpi", type=int, default=200, help="OCR render DPI")
    an.add_argument("--ocr-language", default="eng", help="Tesseract language code, e.g. eng")
    an.add_argument("--output-dir", default="docket_gap_output")
    an.add_argument("--rules", help="Path to rules JSON")
    an.add_argument("--extensions", nargs="+", default=[".pdf", ".zip"])
    an.set_defaults(func=cmd_analyze)

    bat = sub.add_parser("batch", help="Analyze multiple cases from a manifest JSON.")
    bat.add_argument("--artifact-zip", required=True)
    bat.add_argument("--manifest", required=True)
    bat.add_argument("--output-dir", default="docket_gap_output")
    bat.add_argument("--workbook-name", default="docket_gap_download_request_by_case.xlsx")
    bat.add_argument("--rules", help="Path to rules JSON")
    bat.add_argument("--extensions", nargs="+", default=[".pdf", ".zip"])
    bat.set_defaults(func=cmd_batch)

    sp = sub.add_parser("split", help="Split a combined docket text file where a new case starts at entry 1.")
    sp.add_argument("--input-text", required=True)
    sp.add_argument("--output-dir", required=True)
    sp.set_defaults(func=cmd_split)

    auto = sub.add_parser("auto", help="One-click folder-based run: read input/ and write output/.")
    auto.set_defaults(func=cmd_auto)
    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
